replicaCount: 2

image:
  repository: YOUR_DOCKERHUB_USERNAME/gitops-demo-app
  tag: "initial"
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80
  targetPort: 3000
  nodePort: 30080

containerPort: 3000